import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import Typewriter from "typewriter-effect";
import m from "../public/m.jpg";
import aqi from "../public/aqi.png";

export default function Home() {
  var $ = (e) => {
    return document.querySelector(e);
  };

  const [term, setterm] = useState(null);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com/"></script>
      </Head>

      <div id="main-content">
        <div className="lg:pt-[10%] pt-[100px] lg:pl-0 pl-[10px] lg:absolute lg:left-[50%] lg:translate-x-[-50%]">
          <div className="flex lg:flex-row flex-col lg:space-x-5 lg:space-y-0 space-y-6">
            <div className="flex flex-col space-y-2">
              <h1 className="text-3xl lg:text-5xl font-bold">Think...</h1>
              <h1
                className="text-5xl lg:text-7xl font-thin pl-[60px] o"
                id="demo"
              >
                <Typewriter
                  onInit={(typewriter) => {
                    typewriter
                      .typeString("Creative")
                      .pauseFor(2500)
                      .deleteAll()
                      .typeString("Positive")
                      .pauseFor(2500)
                      .deleteAll()
                      .typeString("Deep")
                      .pauseFor(2500)
                      .deleteAll()
                      .typeString("Minimal")
                      .pauseFor(2500)
                      .start();
                  }}
                />
              </h1>
              <br />
              <p className="text-[14px] lg:text-lg text-gray-500 font-semibold">
                Hello there my friend! Welcome to this site. I am Agrim, the
                developer of this site... I can also make one for you. I am a
                frontend developer I really love building websites and to make
                the web better, currently I work with React, Next, TailwindCSS,
                Electron, Python and many more. I can also build a site for you
                :)
              </p>
            </div>
            <img
              className="w-[500px] h-[400px] rounded-lg"
              src="https://images.unsplash.com/photo-1533038590840-1cde6e668a91?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
            />
          </div>
          <br />
          <h1 className="font-bold text-5xl o text-center">For You</h1>
          <br />
          <div className="flex lg:flex-row flex-col lg:ml-[9%] ml-0 lg:justify-start justify-center space-x-24">
            <ul className="flex flex-col">
              <li className="flex flex-col space-y-2">
                <h1 className="text-3xl font-bold o lg:text-left text-center">
                  Temps & AQI
                </h1>
                <p className="lg:text-lg text-[12px] font-bold text-gray-500 lg:text-left text-center">
                  Temps & AQI is a weather / aqi app which lets you know weather{" "}
                  <br />
                  of your city. Also gives a description + wind speed and Air{" "}
                  <br />
                  Quality of the city mentioned.
                </p>
              </li>
              <li className="lg:pl-0 pl-2.5 mt-[30px] flex space-x-2 items-center font-bold">
                <span className="text-green-500 text-2xl">✔</span>
                <span>Free & Open source</span>
              </li>
              <li className="lg:pl-0 pl-2.5 flex space-x-2 items-center font-bold">
                <span className="text-green-500 text-2xl">✔</span>
                <span>Temperature, Wind Speed, Description and AQI</span>
              </li>
              <li className="mt-[30px] flex lg:justify-center justify-center">
                <a href="">
                  <button
                    onClick={(e) => {
                      e.preventDefault();
                      window.open("");
                    }}
                    className="w-[320px] h-[40px] flex justify-center items-center rounded-full bg-blue-500 text-white text-2xl font-bold space-x-2"
                  >
                    <img src="https://img.icons8.com/color/36/000000/linux--v1.png" />{" "}
                    <span>Download for linux</span>{" "}
                  </button>
                </a>
              </li>
            </ul>
            <br />
            <Image
              alt="Refurbish"
              className="ml-[10px] w-[100px] h-[100px] lg:block hidden"
              src={aqi}
              width="360px"
              height="640px"
              id="hidden"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
