import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  var $ = (e) => {
    return document.querySelector(e);
  };

  const [term, setterm] = useState(null);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com/"></script>
      </Head>

      <div
        id="main-content"
        className="lg:pt-[10%] pt-[100px] absolute left-[50%] translate-x-[-50%]"
      >
        <div className="w-[330px] lg:w-[800px] p-3 rounded-lg border-[1px] bg-slate-100">
          <div className="mr-0 ml-auto w-[40px] h-[40px] bg-white rounded-full flex items-center justify-center">
            <img src="https://img.icons8.com/color/36/000000/nextjs.png" />
          </div>
          <h1 className="text-lg font-bold text-gray-500 font-sans">
            Oct 8, 2022
          </h1>
          <h1 className="text-3xl font-bold o">
            5 Next.js projects you must try
          </h1>
          <br />
          <p className="text-gray-500">
            Try these easy and amazing Next.js projects which you can add to
            your work or portfolio.
          </p>
          <Link href="/blogs/five-next-js-projects">
            <button className="bg-blue-500 w-[160px] h-[40px] text-white rounded-full mt-[10px] text-2xl font-bold">
              Read More
            </button>
          </Link>
        </div>
      </div>
      <footer></footer>
    </div>
  );
}
