import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import Typewriter from "typewriter-effect";

export default function Home() {
  var $ = (e) => {
    return document.querySelector(e);
  };

  const [term, setterm] = useState(null);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Get a site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com/"></script>
      </Head>

      <div
        id="main-content"
        className="pt-[5%] lg:pl-0 pl-[10px] lg:absolute lg:left-[50%] lg:translate-x-[-50%]"
      >
        <h1 className="text-5xl font-bold text-center o">Projects</h1>
        <br />
        <h1 className="text-3xl font-semibold text-center">
          <Typewriter
            onInit={function (typewriter) {
              typewriter.typeString("But why?").start();
            }}
          />
        </h1>
        <br />
        <br />
        <div className="flex lg:space-y-0 space-y-2 lg:flex-row flex-col lg:space-x-2 lg:inherit absolute left-[50%] translate-x-[-50%]">
          <div className="w-[330px] p-2.5 lg:w-[400px] rounded-lg border-[1px] border-gray-500">
            <h1 className="o text-3xl font-bold">Typer+</h1>
            <br />
            <p className="lg:text-2xl text-lg text-gray-500">
              A simple and lightweight markdown editor app built on next.js and
              electron.js
            </p>
            <br />
            <hr />
            <br />
            <br />
            <div className="space-y-2">
              <a
                href="https://github.com/agrimCodesLikeIdiot/Typer-Plus"
                target="_blank"
              >
                <button className="w-[100%] transition ease-in-out hover:scale-110 w-[160px] h-[40px] bg-black rounded-full font-bold text-white flex justify-center items-center space-x-2 text-lg ">
                  <span className="text-center flex space-x-2">GitHub</span>{" "}
                </button>
              </a>
            </div>
            <br />
          </div>
        </div>
        <div className="flex lg:space-y-0 space-y-2 lg:flex-row flex-col lg:space-x-2 lg:inherit absolute left-[50%] translate-x-[-50%]">
          <div className="w-[330px] p-2.5 lg:w-[400px] rounded-lg border-[1px] border-gray-500">
            <h1 className="o text-3xl font-bold">Typer+</h1>
            <br />
            <p className="lg:text-2xl text-lg text-gray-500">
              A simple and lightweight markdown editor app built on next.js and
              electron.js
            </p>
            <br />
            <hr />
            <br />
            <br />
            <div className="space-y-2">
              <a
                href="https://github.com/agrimCodesLikeIdiot/Typer-Plus"
                target="_blank"
              >
                <button className="w-[100%] transition ease-in-out hover:scale-110 w-[160px] h-[40px] bg-black rounded-full font-bold text-white flex justify-center items-center space-x-2 text-lg ">
                  <span className="text-center flex space-x-2">GitHub</span>{" "}
                </button>
              </a>
            </div>
            <br />
          </div>
        </div>
        <div className="mt-[530px] mb-[30px] flex justify-center">
          <h1
            onClick={() => router.push("/contact")}
            className="l hover:underline hover:cursor-pointer"
          >
            Feel free to give your feedback!
          </h1>
        </div>
      </div>
      <div id="" className="relative bottom-0 left-0 right-0 w-[100vw]"></div>
    </div>
  );
}
