import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";
import Typewriter from "typewriter-effect";

export default function Home() {
  var $ = (e) => {
    return document.querySelector(e);
  };

  const [term, setterm] = useState(null);
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Get a site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com/"></script>
      </Head>

      <div
        id="main-content"
        className="pt-[180px] lg:pl-0 pl-[10px] lg:absolute lg:left-[50%] lg:translate-x-[-50%]"
      >
        <h1 className="text-5xl font-bold text-center o">
          Get yourself a site
        </h1>
        <br />
        <h1 className="text-3xl font-semibold text-center">
          <Typewriter
            onInit={function (typewriter) {
              typewriter.typeString("But why?").start();
            }}
          />
        </h1>
        <br />
        <br />
        <div className="flex lg:space-y-0 space-y-2 lg:flex-row flex-col lg:space-x-2 lg:inherit absolute left-[50%] translate-x-[-50%]">
          <div className="w-[330px] p-2.5 lg:w-[400px] rounded-lg border-[1px] border-gray-500">
            <h1 className="o text-3xl font-bold">Free</h1>
            <br />
            <p className="lg:text-2xl text-lg text-gray-500">
              This is a free pack for small projects like a web app.
            </p>
            <br />
            <hr />
            <br />
            <br />
            <h1 className="text-2xl o">What do I get for free?</h1>
            <br />
            <ul>
              <li className="text-gray-500 font-bold text-lg">HTML, CSS, JS</li>
              <li className="text-gray-500 font-bold text-lg">Responsive</li>
              <li className="text-gray-500 font-bold text-lg">One page</li>
              <li className="text-gray-500 font-bold text-lg line-through">
                Temparory Hosting
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                Tailwind CSS
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                MPA (HTML, CSS, JS)
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                SPA (React, Next)
              </li>
            </ul>
          </div>
          <div className="w-[330px] p-2.5 lg:w-[400px] rounded-lg border-[1px] border-gray-500">
            <h1 className="o text-3xl font-bold">MPA</h1>
            <br />
            <p className="lg:text-2xl text-lg text-gray-500">
              This is a $2 pack for medium sized projects. Example - Portfolio
            </p>
            <br />
            <hr />
            <br />
            <br />
            <h1 className="text-2xl o">What do I get for $2?</h1>
            <br />
            <ul>
              <li className="text-gray-500 font-bold text-lg">HTML, CSS, JS</li>
              <li className="text-gray-500 font-bold text-lg">Responsive</li>
              <li className="text-gray-500 font-bold text-lg">
                MPA | No. of pages `&gt; 1` or `= 1 `
              </li>
              <li className="text-gray-500 font-bold text-lg">Tailwind CSS</li>
              <li className="text-gray-500 font-bold text-lg">
                Temparory Hosting
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                One page
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                SPA (React, Next)
              </li>
            </ul>
          </div>
          <div className="w-[330px] p-2.5 lg:w-[400px] rounded-lg border-[1px] border-gray-500">
            <h1 className="o text-3xl font-bold">SPA</h1>
            <br />
            <p className="lg:text-2xl text-lg text-gray-500">
              This is a $5 pack for large scale projects. Example - Messanger
              app
            </p>
            <br />
            <hr />
            <br />
            <br />
            <h1 className="text-2xl o">What do I get for $5?</h1>
            <br />
            <ul>
              <li className="text-gray-500 font-bold text-lg">HTML, CSS, JS</li>
              <li className="text-gray-500 font-bold text-lg">Responsive</li>
              <li className="text-gray-500 font-bold text-lg">Tailwind CSS</li>
              <li className="text-gray-500 font-bold text-lg">
                Temparory Hosting
              </li>
              <li className="text-gray-500 font-bold text-lg">
                SPA (React, Next)
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                One page
              </li>
              <li className="text-gray-500 font-bold text-lg line-through">
                MPA (HTML, CSS, JS)
              </li>
            </ul>
          </div>
        </div>
      </div>
      <br />
      <footer></footer>
      <br />
    </div>
  );
}
