import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  var $ = (e) => {
    return document.querySelector(e);
  };

  const [term, setterm] = useState(null);
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com/"></script>
      </Head>

      <nav className="flex p-3"></nav>
      <div
        id="main-content"
        className="lg:pt-[10%] pt-[100px] lg:pl-0 pl-[10px] lg:absolute lg:left-[50%] lg:translate-x-[-50%]"
      >
        <h1 className="text-5xl font-bold o">About Typer+</h1>
        <br />
        <p className="text-[14px] text-base lg:text-lg text-gray-500 tracking-tightest break-words">
          Welcome back, uploaded this blogpost after a long time. In this blog{" "}
          <br />
          post we'll be talking about Typer+, a minimal text editor made by me.
        </p>
        <br />
        <h1 className="text-3xl font-semibold o">What is Typer+?</h1>
        <br />
        <p className="text-[14px] text-base lg:text-lg text-gray-500  tracking-tightest break-words">
          Typer+ Built on Electron and Next frameworks on{" "}
            <a
            href="https://google.com/search?q=JavaScript"
            className="ml-2 mr-2 font-bold text-blue-500 underline"
          >
            JavaScript
          </a>{" "}
          programming language. Electron.js is a framework of JavaScript which{" "}
          <br />
          allows you to make desktop apps, many applications like Visual Studio{" "}
          <br />
          Code, GitHub desktop, Spotify, Discord use this framework. I also used{" "}
          <br />
          next.js on it which helps us to make incredible sites and appes really{" "}
          <br />
          fast and it has great features. Next.js is built on the top of <br />
          React.js which again is a great framework.
        </p>
        <br />
        <h1 className="text-3xl font-semibold o">Download</h1>
        <br />
          <a href="">
          <button
            onClick={(e) => {
              e.preventDefault();
              window.open("https://github.com/agrimCodesLikeIdiot/Typer-Plus");
            }}
            className="w-[320px] h-[40px] flex justify-center items-center rounded-full bg-blue-500 text-white text-2xl font-bold space-x-2"
          >
            <img src="https://img.icons8.com/color/36/000000/linux--v1.png" />{" "}
            <span>Download for linux</span>{" "}
          </button>
        </a>
        <br />
        <h1 className="text-3xl font-semibold o">Why to use Typer+?</h1>
        <br/>
        <p className="text-[14px] text-base lg:text-lg text-gray-500  tracking-tightest break-words">
          Typer+ adds very new features for a text editor for markdown files!
        </p>
        <br />
        <ul className="list-disc pl-[13px]">
          <li>Save & Upload your MD files</li>
          <li>Auto - Close brackets & Quotes</li>
          <li>FOSS</li>
          <li>Docs for MD (3rd party)</li>
          <li>Spell - Check</li>
        </ul>
      </div>
      <footer></footer>
    </div>
  );
}
